name: Xcode Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set default scheme
      run: |
        echo "scheme=Netter" >> $GITHUB_ENV

    - name: Build
      run: |
        xcodebuild build \
          -project Netter.xcodeproj \
          -scheme "$scheme" \
          -destination 'platform=macOS' \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          ENABLE_APP_SANDBOX=NO
